### ISSUE TITLE
error when update from 2.3 to 2.5.1 

### ISSUE THREAD

**Issue by chojuanillo** [cooperl22/laravel-db2#19]
hello. when upgrade to 2.5.1 ... error in line `return sprintf(implode(';', $dsnParts),  ...$dsnConfig);` FatalErrorException' with message 'syntax error, unexpected '.'' 
in /var/www/web/vendor/cooperl/laravel-db2/src/Connectors/ODBCConnector.php:84

**Comment by cooperl22** [comment]
Can you composer update please and see if it works?

Thank you.

**Comment by chojuanillo** [comment]
Hi. thanks for answering. I've done a `composer update` and continues  the same problem.  thank you very much

**Comment by cooperl22** [comment]
You still have the same error?

**Comment by lucasmezencio** [comment]
@chojuanillo this 'error' is caused by the _splat operator_ added in PHP 5.6 on Variadic Functions: http://php.net/manual/en/functions.arguments.php#functions.variable-arg-list.
Actually, it was my mistake, by adding this feature I not updated composer.json.

I will create a PR to work around this bug. Even so, I suggest you upgrade your PHP because the stable version of PHP today is already 7. :smiley:

**Comment by lucasmezencio** [comment]
Oh, I did not noticed, but @cooperl22 has fixed this on another commit: https://github.com/cooperl22/laravel-db2/commit/e26b9b4bcb12a74b198144e16359be5601318c50 :)
